### ISSUE TITLE
Convert logic does not rotate the image upright

### ISSUE THREAD

**Issue by Harun8** [szapp/heic-jpg-exif#1]
First of all awesome implementation, i had a lot of trouble where when i converted from heic to jpg/jpeg it just removed that underlying metadata (including the exif data).

However in your convert module you specify that this following logic rotates the image upright, but through different test it does not seem to do it. And i usually deal with quite a lot of heic images that are rotated differently, and we want to store the image in it's "correct orientation" 
`
  // Conversion rotates the image upright
  if (ifd0[piexif.TagValues.ImageIFD.Orientation] > 4) {
    const xd = exif[piexif.TagValues.ExifIFD.PixelXDimension]
    const yd = exif[piexif.TagValues.ExifIFD.PixelYDimension]
    exif[piexif.TagValues.ExifIFD.PixelXDimension] = yd
    exif[piexif.TagValues.ExifIFD.PixelYDimension] = xd
    ifd0[piexif.TagValues.ImageIFD.Orientation] = 1
  }`

This is my implementation: 

`     if (fileExtension === "heic") {
        const outBuffer = await convert(file.buffer, undefined, 0.7);
        fileObj = {
          originalname: file.originalname,
          buffer: outBuffer,
        };
      }
`

Thank you very much

**Comment by szapp** [comment]
Thanks for your interest and for raising this issue!

From my testing, I found that heic-convert (the excellent npm package used for the actual conversion underneath) produces JPG images that are upright with respect to the orientation specified in the Image EXIF-tag "Orientation". Such that the tag needs to be reset in the resulting JPG.

Specifically, if I have a HEIC photo shot on my phone in portrait, the Orientation tag will be 6 (Rotate 90 CW). The conversion produces the JPG natively in portrait mode making the Orientation tag actually rotating the already rotated image another 90 degrees. That's why it is removed in the code you referenced.

However, this is based on my limited testing with only a handful out of the possible 8 rotations.

I would love to look into this! Could you provide me with an example picture where you observe the incorrect rotation? Preferably stripped of any sensitive metadata (like GPS location) and content.

**Comment by szapp** [comment]
Quick note:

After some research, it looks like the EXIF orientation via the Orientation-flag is not relevant in the HEIC format. The image rotation is realized with an internal Rotation-flag (0, 90, 180, 270). When decoding the HEIC image the rotation seems to be implicit, resulting in a correctly rotated JPG after conversion. The EXIF orientation has to then be reset.

Before, the orientation flag was only reset for some rotations - now this EXIF flag is reset always.  
Would you try again with heic-jpg-exif v0.3.5? (There were some faulty releases in between when porting to TypeScript.)

Feel free to still send me example images with which you experience problems!

**Comment by Harun8** [comment]
First of all sorry for such an late answer.

It still seems like it doesn't rotate the image. And I might suspect why. So let me just explain what I did, so you have a chance to get an overview

1. I took an image on my Iphone rotated the image after with 190 (red. upside down)
2. Downloaded the image in heic format
3. I then checked the image exif data before using your package. And under orientation it says horizontal(normal), and rotation(0) shown on the image too. 
4. Even though I clearly rotated it. And note this even before I use your package. So I think the error is on my side with my iphone. But I am thoroughly confused on why the iphone doesn't set the rotation number to 3 (which is what a 180 image is  according to this website: https://sirv.com/help/articles/rotate-photos-to-be-upright/)
![image](https://github.com/szapp/heic-jpg-exif/assets/66841357/dd586401-17c2-4b7f-b9ee-68ed4377513c)
![image](https://github.com/szapp/heic-jpg-exif/assets/66841357/cba5da6b-02a0-46a5-952a-bc787733b558)
